name: Filter Issues CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "*/60 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install node required
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies 1
        run: npm ci

      - name: run hello.js
        run: |
          node ./hello.js

      - name: Install dependencies 2
        run: npm ci

      - name: Install dependencies 3
        run: npm ci

      - name: Any how this step should run
        if: always()
        run: |
          curl -XPOST -d '{"msgtype": "m.text","body": "", "format": "org.matrix.custom.html","formatted_body": "<a href='https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/job/$GITHUB_JOB'>NC-Nightly(master)</a><br></br><b><i>Status: ${{ job.status }}</i></b>"}' "${{secrets.ELEMENT_BASE_URL}}/_matrix/client/r0/rooms/%21${{secrets.ELEMENT_ROOM_ID}}/send/m.room.message?access_token=${{secrets.ELEMENT_BOT_TOKEN}}"