name: Filter Issues CI/CD from try_cron branch

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, try_cron]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout code
        uses: actions/checkout@v3

      - name: Install node required
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci
