name: Build Template

on:
  push:
    branches:
      - ${{ matrix.branch }}
  schedule:
    - cron: '0 0 * * *' # Schedule to run daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [main]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install