name: Nightly-try_cron

on:
  push:
    branches-ignore:
      - main
  schedule:
    - cron: "*/60 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: try_cron

      - name: Install node required
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: run hello.js
        run: |
          node ./hello.js

      - name: Any how this step should run
        if: always()
        run: |
          echo "This Step is running even if the build failed"
