name: Filter Issues CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # schedule:
  #   - cron: "*/6 * * * *"

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - try_cron
    steps:
      - name: scheduled
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - name: Install node required
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: run hello.js
        run: |
          node ./hello.js
