name: Filter Issues CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "00 04 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Chekout code
      uses: actions/checkout@v3

    - name: Install node required 
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    
    - name: Install dependencies
      run: npm ci

    - name: Clone ocis and web
      run: |
        git clone https://github.com/owncloud/ocis.git
        git clone https://github.com/owncloud/web.git

    - name: Check closed issue for ocis
      env:
        PATH_TO_EXPECTED_TO_FAILURE: ocis/tests/acceptance
      run: npm start

    - name: Push notification to rocket.chat if the job failed
      id: error-notification
      if: ${{ failure() }}
      uses: jadolg/rocketchat-notification-action@v1.0.1
      with:
        server: ${{ secrets.ROCKETCHAT_SERVER }}
        message: Job Failed !! There might be some expected to failure issues that has been closed !!!!
        user: ${{ secrets.ROCKETCHAT_USER }}
        password: ${{ secrets.ROCKETCHAT_PASSWORD }}
        channel: Test-Channel