# File: .github/workflows/main.yml
name: Filter Issues CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # schedule:
  #   - cron: "*/6 * * * *"

jobs:
  main:
    if: github.event_name != 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Common steps
        uses: ./.github/workflows/common.yml

      - name: run hello.js
        run: |
          node ./hello.js
