name: Nightly-try_cron

on:
  push:
    branches-ignore:
      - main
  schedule:
    - cron: "*/6 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: try_cron

      - name: Install node required
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: run hello.js
        run: |
          node ./hello.js

      - name: Any how this step should run
        if: always()
        run: |
          echo "This Step is running even if the build failed"

      - name: Any how this step should run
        if: always() && github.event_name == 'schedule'
        run: |
          curl -XPOST -d '{"msgtype": "m.text","body": "", "format": "org.matrix.custom.html","formatted_body": "<a href='https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID'>CHECK-EXPECTED-NIGHTLY-(${{ github.ref }})</a><br></br><b><i>Status: ${{ job.status }}</i></b>"}' "${{secrets.ELEMENT_BASE_URL}}/_matrix/client/r0/rooms/%21${{secrets.ELEMENT_ROOM_ID}}/send/m.room.message?access_token=${{secrets.ELEMENT_BOT_TOKEN}}"
