# File: .github/workflows/common.yml
name: Nightly CI

on:
  push:
    branches: [main]

jobs:
  nightly:
    runs-on: ubuntu-latest

    # Reference the reusable workflow
    steps:
      - name: Reuse Print Message
        uses: ./.github/workflows/actionsMain.yml@common
