name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "*/6 * * * *"
  workflow_run:
    workflows:
      - "Name of Your Workflow"
    types:
      - completed

jobs:
  main:
    uses: ./.github/workflows/shared_steps.yml
    with:
      branch: main
