name: Release Workflow

on:
  push:
    branches:
      - try_cron
  pull_request:
    branches:
      - try_cron
  schedule:
    - cron: "*/60 * * * *"

jobs:
  try_cron:
    uses: ./.github/workflows/shared_steps.yml
    secrets: inherit
    with:
      branch: try_cron
