name: Shared Steps

on:
  workflow_call:
    inputs:
      branch:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - name: Get branch name
        run: |
          echo "Branch name from shared: ${{ inputs.branch }}"

      - name: Install node required
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: run hello.js
        run: |
          node ./hello.js
