name: Shared Steps

on:
  workflow_call:
    inputs:
      branch:
        type: string

  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - name: Get branch name
        run: |
          echo "Branch name from trigger: ${{ inputs.branch }}"

      - name: Install node required
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: run hello.js
        run: |
          node ./hello.js

  api-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - name: Get branch name
        run: |
          echo "Branch name from trigger: ${{ inputs.branch }}"

      - name: Install node required
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: run hello.js
        run: |
          node ./hello.js

  overall-status:
    runs-on: ubuntu-latest

    needs: [unit-test, api-test] # This job depends on the success of both 'unit-test' and 'api-test'

    steps:
      - name: Check overall status
        run: |
          if [ "${{ job.status }}" != "success" ]; then
            echo "One or more jobs failed!"
            exit 1
          else
            echo "All jobs passed successfully."
          fi
