name: Shared Steps

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - name: Get branch name
        run: |
          echo "Branch name from trigger: ${{ inputs.branch }}"

      - name: Install node required
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: run hello.js
        run: |
          node ./hello.js

  api-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - name: Get branch name
        run: |
          echo "Branch name from trigger: ${{ inputs.branch }}"

      - name: Install node required
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: run hello.js
        run: |
          node ./hello.js

  notify:
    needs:
      - unit-test
      - api-test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Step 2
        run: |
          echo "workflow run ID: ${{ github.run_id }}"
